services:
  - type: web
    name: epm-builder-frontend
    runtime: static
    rootDir: epm-builder/frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://compact-nissy-modelling-assistant-3106933b.koyeb.app/api
    autoDeploy: true
