name: Run Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gams/gams:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Inject GAMS license
        env:
          GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
        run: |
          echo "$GAMS_LICENSE" > /gams/gamslice.txt
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Python script (depends on GAMS)
        run: |
          python epm/epm.py --simple --solver RMIP --folder_input data_test --config config.csv
